steps:
  
  - id: go_test
    name: 'gcr.io/cloud-builders/go'
    args: ['test','./go_server']
    env: ['GOPATH=.','CGO_ENABLED=0']

  - id: "Building image from Dockerfile"
    name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafio-k8s-go:$SHORT_SHA', '-f', 'Dockerfile', './go_server']

  - id: "Pushing image"
    name: 'docker'
    args: ['push', 'gcr.io/$PROJECT_ID/desafio-k8s-go:$SHORT_SHA']

  - id: "Adjusting deployment file - k8s"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "/bin/sh"
    args:
        - "-c"
        - |
            sed 's#img-app-deployment#gcr.io/$PROJECT_ID/desafio-k8s-go:$SHORT_SHA#g' go_server/k8s/deployment.yaml > go_server/k8s/deployment-new.yaml
            cat go_server/k8s/deployment-new.yaml;

  - id: "Deploying k8s"
    name: "gcr.io/cloud-builders/kubectl"
    args: 
        - "apply"
        - "-f"
        - "k8s/app/deployment-new.yaml"
    env:
    - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
    - "CLOUDSDK_CONTAINER_CLUSTER=cluster-1"

tags: ['cloud-builders-community']