steps:
  
  - id: go_test
    name: 'gcr.io/cloud-builders/go'
    args: ['test','./go_server']
    env: ['GOPATH=.','CGO_ENABLED=0']

  - id: go_build
    name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', './go_server', './go_server']
    env: ['GOPATH=.']

  - id: docker_build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/desafio-k8s-go:latest', './go_server/']

images:
  - 'gcr.io/$PROJECT_ID/desafio-k8s-go:latest'