steps:
  
  - id: go_test
    name: 'gcr.io/cloud-builders/go'
    args: ['test','./go_server']
    env: ['GOPATH=.','CGO_ENABLED=0']

  - id: go_build
    name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', './go_server', './go_server']
    env: ['GOPATH=.']

  - id: docker_build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/desafio-k8s-go:latest', './go_server/']

  - id: "Ajustando arquivo deployment - k8s"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "/bin/sh"
    args:
        - "-c"
        - |
            sed 's#img-app-deployment#gcr.io/$PROJECT_ID/desafio-k8s-go:$SHORT_SHA#g' k8s/deployment.yaml > k8s/deployment-new.yaml
            cat k8s/deployment-new.yaml;

  - id: "Deploying k8s"
    name: "gcr.io/cloud-builders/kubectl"
    args: 
        - "apply"
        - "-f"
        - "k8s/app/deployment-new.yaml"
    env:
    - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
    - "CLOUDSDK_CONTAINER_CLUSTER=cluster-1"


images:
  - 'gcr.io/$PROJECT_ID/desafio-k8s-go:latest'